/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  anon_sym_language_EQ = 2,
  anon_sym_global = 3,
  aux_sym_python_global_block_token1 = 4,
  anon_sym_endglobal = 5,
  sym__line = 6,
  sym_language_name = 7,
  anon_sym_snippet = 8,
  anon_sym_endsnippet = 9,
  sym_text = 10,
  anon_sym_BQUOTE_BANGp = 11,
  anon_sym_BQUOTE = 12,
  sym_python_inline = 13,
  sym_source_file = 14,
  sym__language_declaration = 15,
  sym_python_global_block = 16,
  sym_python_global_block_concat = 17,
  sym_snippet_block = 18,
  sym__python_code = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_python_global_block_concat_repeat1 = 21,
  aux_sym_snippet_block_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_language_EQ] = "language=",
  [anon_sym_global] = "global",
  [aux_sym_python_global_block_token1] = "python_global_block_token1",
  [anon_sym_endglobal] = "endglobal",
  [sym__line] = "_line",
  [sym_language_name] = "language_name",
  [anon_sym_snippet] = "snippet",
  [anon_sym_endsnippet] = "endsnippet",
  [sym_text] = "text",
  [anon_sym_BQUOTE_BANGp] = "`!p",
  [anon_sym_BQUOTE] = "`",
  [sym_python_inline] = "python_inline",
  [sym_source_file] = "source_file",
  [sym__language_declaration] = "_language_declaration",
  [sym_python_global_block] = "python_global_block",
  [sym_python_global_block_concat] = "python_global_block_concat",
  [sym_snippet_block] = "snippet_block",
  [sym__python_code] = "_python_code",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_python_global_block_concat_repeat1] = "python_global_block_concat_repeat1",
  [aux_sym_snippet_block_repeat1] = "snippet_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_language_EQ] = anon_sym_language_EQ,
  [anon_sym_global] = anon_sym_global,
  [aux_sym_python_global_block_token1] = aux_sym_python_global_block_token1,
  [anon_sym_endglobal] = anon_sym_endglobal,
  [sym__line] = sym__line,
  [sym_language_name] = sym_language_name,
  [anon_sym_snippet] = anon_sym_snippet,
  [anon_sym_endsnippet] = anon_sym_endsnippet,
  [sym_text] = sym_text,
  [anon_sym_BQUOTE_BANGp] = anon_sym_BQUOTE_BANGp,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_python_inline] = sym_python_inline,
  [sym_source_file] = sym_source_file,
  [sym__language_declaration] = sym__language_declaration,
  [sym_python_global_block] = sym_python_global_block,
  [sym_python_global_block_concat] = sym_python_global_block_concat,
  [sym_snippet_block] = sym_snippet_block,
  [sym__python_code] = sym__python_code,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_python_global_block_concat_repeat1] = aux_sym_python_global_block_concat_repeat1,
  [aux_sym_snippet_block_repeat1] = aux_sym_snippet_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_language_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_python_global_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_endglobal] = {
    .visible = true,
    .named = false,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_language_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_snippet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endsnippet] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BANGp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_python_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__language_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_python_global_block] = {
    .visible = true,
    .named = true,
  },
  [sym_python_global_block_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_snippet_block] = {
    .visible = true,
    .named = true,
  },
  [sym__python_code] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_python_global_block_concat_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_snippet_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_language = 1,
  field_python = 2,
  field_python_inline = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_language] = "language",
  [field_python] = "python",
  [field_python_inline] = "python_inline",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_language, 0, .inherited = true},
  [1] =
    {field_language, 2},
  [2] =
    {field_python_inline, 0, .inherited = true},
  [3] =
    {field_python, 2},
  [4] =
    {field_python_inline, 2, .inherited = true},
  [5] =
    {field_python_inline, 0, .inherited = true},
    {field_python_inline, 1, .inherited = true},
  [7] =
    {field_python_inline, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '`') ADVANCE(76);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'g') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 's') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '`') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == 'e') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == '`') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'b') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(25);
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 40:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_language_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_python_global_block_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_python_global_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_endglobal);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_endglobal);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'b') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'd') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'g') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'l') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'l') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'n') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_language_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_snippet);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_endsnippet);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_endsnippet);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BANGp);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_python_inline);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_python_inline);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(78);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 45},
  [24] = {.lex_state = 45},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_language_EQ] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_endglobal] = ACTIONS(1),
    [anon_sym_snippet] = ACTIONS(1),
    [anon_sym_endsnippet] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(21),
    [sym__language_declaration] = STATE(2),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      anon_sym_global,
    ACTIONS(9), 1,
      anon_sym_snippet,
    STATE(7), 1,
      sym_python_global_block,
    STATE(6), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [17] = 5,
    ACTIONS(11), 1,
      anon_sym_endsnippet,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BANGp,
    STATE(5), 1,
      aux_sym_snippet_block_repeat1,
    STATE(14), 1,
      sym__python_code,
  [33] = 5,
    ACTIONS(17), 1,
      anon_sym_endsnippet,
    ACTIONS(19), 1,
      sym_text,
    ACTIONS(22), 1,
      anon_sym_BQUOTE_BANGp,
    STATE(4), 1,
      aux_sym_snippet_block_repeat1,
    STATE(14), 1,
      sym__python_code,
  [49] = 5,
    ACTIONS(15), 1,
      anon_sym_BQUOTE_BANGp,
    ACTIONS(25), 1,
      anon_sym_endsnippet,
    ACTIONS(27), 1,
      sym_text,
    STATE(4), 1,
      aux_sym_snippet_block_repeat1,
    STATE(14), 1,
      sym__python_code,
  [65] = 3,
    ACTIONS(9), 1,
      anon_sym_snippet,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [76] = 3,
    ACTIONS(9), 1,
      anon_sym_snippet,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(8), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [87] = 3,
    ACTIONS(9), 1,
      anon_sym_snippet,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [98] = 3,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_snippet,
    STATE(9), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [109] = 1,
    ACTIONS(38), 3,
      ts_builtin_sym_end,
      anon_sym_global,
      anon_sym_snippet,
  [115] = 3,
    ACTIONS(40), 1,
      sym__line,
    STATE(12), 1,
      aux_sym_python_global_block_concat_repeat1,
    STATE(26), 1,
      sym_python_global_block_concat,
  [125] = 3,
    ACTIONS(42), 1,
      anon_sym_endglobal,
    ACTIONS(44), 1,
      sym__line,
    STATE(15), 1,
      aux_sym_python_global_block_concat_repeat1,
  [135] = 1,
    ACTIONS(46), 3,
      anon_sym_endsnippet,
      sym_text,
      anon_sym_BQUOTE_BANGp,
  [141] = 1,
    ACTIONS(48), 3,
      anon_sym_endsnippet,
      sym_text,
      anon_sym_BQUOTE_BANGp,
  [147] = 3,
    ACTIONS(50), 1,
      anon_sym_endglobal,
    ACTIONS(52), 1,
      sym__line,
    STATE(15), 1,
      aux_sym_python_global_block_concat_repeat1,
  [157] = 1,
    ACTIONS(55), 3,
      anon_sym_endsnippet,
      sym_text,
      anon_sym_BQUOTE_BANGp,
  [163] = 2,
    ACTIONS(57), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      sym_python_inline,
  [170] = 1,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [175] = 1,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [180] = 1,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [185] = 1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
  [189] = 1,
    ACTIONS(69), 1,
      anon_sym_language_EQ,
  [193] = 1,
    ACTIONS(71), 1,
      aux_sym_python_global_block_token1,
  [197] = 1,
    ACTIONS(73), 1,
      aux_sym_python_global_block_token1,
  [201] = 1,
    ACTIONS(75), 1,
      sym_language_name,
  [205] = 1,
    ACTIONS(77), 1,
      anon_sym_endglobal,
  [209] = 1,
    ACTIONS(79), 1,
      anon_sym_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 33,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 65,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 87,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 109,
  [SMALL_STATE(11)] = 115,
  [SMALL_STATE(12)] = 125,
  [SMALL_STATE(13)] = 135,
  [SMALL_STATE(14)] = 141,
  [SMALL_STATE(15)] = 147,
  [SMALL_STATE(16)] = 157,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 170,
  [SMALL_STATE(19)] = 175,
  [SMALL_STATE(20)] = 180,
  [SMALL_STATE(21)] = 185,
  [SMALL_STATE(22)] = 189,
  [SMALL_STATE(23)] = 193,
  [SMALL_STATE(24)] = 197,
  [SMALL_STATE(25)] = 201,
  [SMALL_STATE(26)] = 205,
  [SMALL_STATE(27)] = 209,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 2, 0, 6),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 2, 0, 6), SHIFT_REPEAT(4),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 2, 0, 6), SHIFT_REPEAT(17),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__language_declaration, 3, 0, 2),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_global_block_concat, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__python_code, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 1, 0, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_python_global_block_concat_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_python_global_block_concat_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__python_code, 3, 0, 7),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_block, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_global_block, 4, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_block, 4, 0, 5),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_snippets(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "snippets",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 7,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
