/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  anon_sym_language_EQ = 2,
  sym_line = 3,
  sym_language_name = 4,
  anon_sym_snippet = 5,
  aux_sym_snippet_block_token1 = 6,
  anon_sym_endsnippet = 7,
  sym_source_file = 8,
  sym_language_declaration = 9,
  sym_snippet_block = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_snippet_block_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_language_EQ] = "language=",
  [sym_line] = "line",
  [sym_language_name] = "language_name",
  [anon_sym_snippet] = "snippet",
  [aux_sym_snippet_block_token1] = "snippet_block_token1",
  [anon_sym_endsnippet] = "endsnippet",
  [sym_source_file] = "source_file",
  [sym_language_declaration] = "language_declaration",
  [sym_snippet_block] = "snippet_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_snippet_block_repeat1] = "snippet_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_language_EQ] = anon_sym_language_EQ,
  [sym_line] = sym_line,
  [sym_language_name] = sym_language_name,
  [anon_sym_snippet] = anon_sym_snippet,
  [aux_sym_snippet_block_token1] = aux_sym_snippet_block_token1,
  [anon_sym_endsnippet] = anon_sym_endsnippet,
  [sym_source_file] = sym_source_file,
  [sym_language_declaration] = sym_language_declaration,
  [sym_snippet_block] = sym_snippet_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_snippet_block_repeat1] = aux_sym_snippet_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_language_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_language_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_snippet] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_snippet_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_endsnippet] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_language_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_snippet_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_snippet_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 's') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == 'e') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(3);
      END_STATE();
    case 25:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_language_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'd') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'n') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'n') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'p') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 's') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_language_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_snippet);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_snippet_block_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_snippet_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_endsnippet);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_endsnippet);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 42},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 25},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_language_EQ] = ACTIONS(1),
    [anon_sym_snippet] = ACTIONS(1),
    [anon_sym_endsnippet] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym_language_declaration] = STATE(2),
    [sym_snippet_block] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_snippet] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(7), 1,
      anon_sym_snippet,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [11] = 3,
    ACTIONS(7), 1,
      anon_sym_snippet,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [22] = 3,
    ACTIONS(7), 1,
      anon_sym_snippet,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [33] = 3,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_snippet,
    STATE(5), 2,
      sym_snippet_block,
      aux_sym_source_file_repeat1,
  [44] = 3,
    ACTIONS(18), 1,
      sym_line,
    ACTIONS(20), 1,
      anon_sym_endsnippet,
    STATE(7), 1,
      aux_sym_snippet_block_repeat1,
  [54] = 3,
    ACTIONS(22), 1,
      sym_line,
    ACTIONS(24), 1,
      anon_sym_endsnippet,
    STATE(8), 1,
      aux_sym_snippet_block_repeat1,
  [64] = 3,
    ACTIONS(26), 1,
      sym_line,
    ACTIONS(29), 1,
      anon_sym_endsnippet,
    STATE(8), 1,
      aux_sym_snippet_block_repeat1,
  [74] = 1,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [79] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [84] = 1,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_snippet,
  [89] = 1,
    ACTIONS(37), 1,
      anon_sym_language_EQ,
  [93] = 1,
    ACTIONS(39), 1,
      aux_sym_snippet_block_token1,
  [97] = 1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
  [101] = 1,
    ACTIONS(43), 1,
      sym_language_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 11,
  [SMALL_STATE(4)] = 22,
  [SMALL_STATE(5)] = 33,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 64,
  [SMALL_STATE(9)] = 74,
  [SMALL_STATE(10)] = 79,
  [SMALL_STATE(11)] = 84,
  [SMALL_STATE(12)] = 89,
  [SMALL_STATE(13)] = 93,
  [SMALL_STATE(14)] = 97,
  [SMALL_STATE(15)] = 101,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_snippet_block_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_language_declaration, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_block, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_block, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_snippets(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
